user:
  api/v1/ingredients/{id}:
    "read:any": ["*"]
    "update:own": ["*"]
    "delete:own": ["*"]
  api/v1/ingredients:
    "read:any": ["*"]
    "create:any": ["*"]
admin:
  api/v1/ingredients:
    "read:any": ["*"]
    "create:any": ["*"]
  api/v1/ingredients/{id}:
    "read:any": ["*"]
    "update:any": ["*"]
    "delete:any": ["*"]